// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://jcnxwshydnthtjppprkf.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Impjbnh3c2h5ZG50aHRqcHBwcmtmIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDM0MzQ4MTYsImV4cCI6MjA1OTAxMDgxNn0.jZE1Pn2fzDWh5E4vEx6-OH8bzyIRzFyF0zIz0YwVfzg";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);